# Generated by Django 3.0.2 on 2020-03-17 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id_cajero', models.AutoField(db_column='id_cajero', primary_key=True, serialize=False)),
                ('nombre_cajero', models.CharField(db_column='nombre_cajero', max_length=15)),
                ('clave_cajero', models.CharField(db_column='clave_cajero', max_length=15)),
                ('estado_cajero', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_column='estado_cajero', default='activo', max_length=10)),
            ],
            options={
                'db_table': 'cajero',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CartonCartas',
            fields=[
                ('id_c_c', models.AutoField(db_column='id_c_c', primary_key=True, serialize=False)),
                ('alta_baja', models.TextField(db_column='alta_baja')),
                ('color', models.TextField(db_column='COLOR')),
                ('valor_apuesta_c', models.IntegerField(db_column='valor_apuesta_c')),
                ('fecha_cartas', models.TextField(db_column='fecha_cartas')),
                ('hora_cartas', models.TextField(db_column='hora_cartas')),
                ('id_cajero', models.ForeignKey(db_column='id_cajero', on_delete=django.db.models.deletion.DO_NOTHING, to='pv.Cajero')),
            ],
            options={
                'db_table': 'carton_cartas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CartonKeno',
            fields=[
                ('id_c_k', models.AutoField(db_column='id_c_k', primary_key=True, serialize=False)),
                ('apuesta_keno', models.TextField(db_column='apuesta_keno')),
                ('valor_apuesta_k', models.IntegerField(db_column='valor_apuesta_k')),
                ('fecha_keno', models.TextField(db_column='fecha_keno')),
                ('hora_keno', models.TextField(db_column='hora_keno')),
                ('id_cajero', models.ForeignKey(db_column='id_cajero', on_delete=django.db.models.deletion.DO_NOTHING, to='pv.Cajero')),
            ],
            options={
                'db_table': 'carton_keno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GanadoresJackpot',
            fields=[
                ('id_ganadores_j', models.AutoField(db_column='id_ganadores_j', primary_key=True, serialize=False)),
                ('valor_ganado_j', models.IntegerField(db_column='valor_ganado_j')),
                ('fecha_ganadores_j', models.TextField(db_column='fecha_ganadores_j')),
                ('hora_ganadores_j', models.TextField(db_column='hora_ganadores_j')),
                ('id_c_k', models.IntegerField(db_column='ID_C_K')),
            ],
            options={
                'db_table': 'ganadores_jackpot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Jackpot',
            fields=[
                ('id_jackpot', models.AutoField(db_column='id_jackpot', primary_key=True, serialize=False)),
                ('monto_actual', models.IntegerField(db_column='monto_actual')),
                ('monto_activacion_j', models.IntegerField(db_column='monto_activacion_j')),
                ('activacion_bono', models.IntegerField(db_column='activacion_bono')),
                ('aumento_jackpot', models.FloatField(db_column='aumento_jackpot')),
            ],
            options={
                'db_table': 'jackpot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(db_column='id_localidad', primary_key=True, serialize=False)),
                ('nombre_localidad', models.CharField(db_column='nombre_localidad', max_length=15)),
            ],
            options={
                'db_table': 'localidad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sorteos',
            fields=[
                ('id_sorteos', models.AutoField(db_column='id_sorteos', primary_key=True, serialize=False)),
                ('numeros_sorteos', models.IntegerField(db_column='numeros_sorteos')),
                ('bonos', models.TextField(db_column='BONOS')),
                ('carta_ganadora', models.IntegerField(db_column='carta_ganadora')),
                ('fecha_sorteos', models.TextField(db_column='fecha_sorteos')),
                ('hora_sorteos', models.TextField(db_column='hora_sorteos')),
                ('estado_sorteos', models.TextField(db_column='estado_sorteos')),
                ('numero_carta', models.IntegerField(db_column='numero_carta')),
            ],
            options={
                'db_table': 'SORTEOS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id_pv', models.AutoField(db_column='id_pv', primary_key=True, serialize=False)),
                ('nombre_pv', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_pv', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_column='estado_pv', default='activo', max_length=10)),
                ('id_localidad', models.ForeignKey(db_column='id_localidad', on_delete=django.db.models.deletion.CASCADE, to='pv.Localidad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'punto_venta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PosPc',
            fields=[
                ('id_pos_pc', models.AutoField(db_column='id_pos_pc', primary_key=True, serialize=False)),
                ('codigo_pos_pc', models.IntegerField(db_column='codigo_pos_pc')),
                ('estado_pos_pc', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_column='estado_pos_pc', default='activo', max_length=10)),
                ('id_pv', models.ForeignKey(db_column='id_pv', on_delete=django.db.models.deletion.DO_NOTHING, to='pv.PuntoVenta')),
            ],
            options={
                'db_table': 'pos_pc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GanadoresKeno',
            fields=[
                ('id_ganadores_k', models.AutoField(db_column='id_ganadores_k', primary_key=True, serialize=False)),
                ('valor_ganado_k', models.IntegerField(db_column='valor_ganado_k')),
                ('fecha_ganadores_k', models.TextField(db_column='fecha_ganadores_k')),
                ('hora_ganadores_k', models.TextField(db_column='hora_ganadores_k')),
                ('id_c_k', models.ForeignKey(db_column='id_c_k', on_delete=django.db.models.deletion.DO_NOTHING, to='pv.CartonKeno')),
            ],
            options={
                'db_table': 'ganadores_keno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GanadoresCartas',
            fields=[
                ('id_ganadores_c', models.AutoField(db_column='id_ganadores_c', primary_key=True, serialize=False)),
                ('valor_ganado_c', models.IntegerField(db_column='valor_ganado_c')),
                ('fecha_ganadores_c', models.TextField(db_column='fecha_ganadores_c')),
                ('hora_ganadores_c', models.TextField(db_column='hora_ganadores_c')),
                ('id_c_c', models.ForeignKey(db_column='id_c_c', on_delete=django.db.models.deletion.DO_NOTHING, to='pv.CartonCartas')),
            ],
            options={
                'db_table': 'ganadores_cartas',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cartonkeno',
            name='id_sorteos',
            field=models.ForeignKey(db_column='id_sorteos', on_delete=django.db.models.deletion.DO_NOTHING, to='pv.Sorteos'),
        ),
        migrations.AddField(
            model_name='cartoncartas',
            name='id_sorteos',
            field=models.ForeignKey(db_column='id_sorteos', on_delete=django.db.models.deletion.DO_NOTHING, to='pv.Sorteos'),
        ),
        migrations.AddField(
            model_name='cajero',
            name='id_pos_pc',
            field=models.ForeignKey(db_column='id_pos_pc', on_delete=django.db.models.deletion.DO_NOTHING, to='pv.PosPc'),
        ),
    ]
