# Generated by Django 3.0.2 on 2020-03-17 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoncartas',
            name='id_cajero',
            field=models.ForeignKey(db_column='id_cajero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pv.Cajero'),
        ),
        migrations.AlterField(
            model_name='cartoncartas',
            name='id_sorteos',
            field=models.ForeignKey(db_column='id_sorteos', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pv.Sorteos'),
        ),
        migrations.AlterField(
            model_name='cartonkeno',
            name='id_cajero',
            field=models.ForeignKey(db_column='id_cajero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pv.Cajero'),
        ),
        migrations.AlterField(
            model_name='cartonkeno',
            name='id_sorteos',
            field=models.ForeignKey(db_column='id_sorteos', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pv.Sorteos'),
        ),
    ]
